### ISSUE TITLE
Desktop toggles not working on desktop / large tablet

### ISSUE THREAD

**Issue by SmashBrando** [digitoimistodude/air#4]
The dropdown button toggle on desktop / large tablet doesn't seem to toggle the menu. When pressing the button the aria role and class never change.

**Comment by ronilaukkarinen** [comment]
Oh yes, that is true. Air is not yet tested on large/desktop touch devices and the navigation is designed to be mobile nav on touch devices at this time. It's possible to have this fixed in [responsive-nav.custom.js](https://github.com/digitoimistodude/air/blob/master/js/src/responsive-nav.custom.js), but I currently have no time to investigate. Pull requests are more than welcome! :)

**Comment by ronilaukkarinen** [comment]
Made some improvements to this in some point. Just tested with large iPad and at least iOS 10 touch events do work currently. If you are still experiencing problems with toggles, please reopen or comment the issue. Thanks!
